F90 = gfortran
CC = gcc
LIBS = -lm -lgfortran -LNN -lnn
##
## build version debug
#FLAGS =  -c -fbounds-check -O0 -g -ggdb  -ffree-line-length-400 -Wmaybe-uninitialized
#CFLAGS = -c -O0 -g -ggdb -Wall
#INCLUDE =
#OPTIONS =  -O0 -g -ggdb
##
#build version release
FLAGS =  -c -fbounds-check -O2  -ffree-line-length-400 -mcmodel=small -fopenmp 
CFLAGS = -c -O2 -mcmodel=small -fopenmp
INCLUDE =
OPTIONS =  -O2 -mcmodel=small -fopenmp
